// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHuSGd7Ey-Kz07Ly4Xxi5iN89REwycVs',
    appId: '1:209138929253:web:931838ed2b18ec1fab008c',
    messagingSenderId: '209138929253',
    projectId: 'test-9480d',
    authDomain: 'test-9480d.firebaseapp.com',
    storageBucket: 'test-9480d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkb3EsIJ_RxIyHgB59alvw5PRjEhSYLI',
    appId: '1:209138929253:android:bc52a1469f7f1df5ab008c',
    messagingSenderId: '209138929253',
    projectId: 'test-9480d',
    storageBucket: 'test-9480d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSyp230LTb4oec0eLU1wLb2RBP-Gt4YOo',
    appId: '1:209138929253:ios:a93ae3aa744191aeab008c',
    messagingSenderId: '209138929253',
    projectId: 'test-9480d',
    storageBucket: 'test-9480d.appspot.com',
    iosBundleId: 'com.example.temp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSyp230LTb4oec0eLU1wLb2RBP-Gt4YOo',
    appId: '1:209138929253:ios:3f9c7ad9f399a71bab008c',
    messagingSenderId: '209138929253',
    projectId: 'test-9480d',
    storageBucket: 'test-9480d.appspot.com',
    iosBundleId: 'com.example.temp2.RunnerTests',
  );
}
